### ISSUE TITLE
Problem with docker

### ISSUE THREAD

**Issue by mfigat** [lulav/ros2_fprime_bridge#18]
# Docker command finishes with an error 
Hi. I followed your steps presented in the tutorial. When I run a command: docker-compose up, I get an error:

```bash
-- Installation directory: /workspaces/ros2_fprime_bridge/fprime_ws/spring/build-artifacts
-- Performing CMake source prescan
CMake Error at /usr/share/cmake-3.22/Modules/FindProtobuf.cmake:272 (message):
  Error: PROTOBUF_GENERATE_CPP() called without any proto files
Call Stack (most recent call first):
  ros2_bridge/CMakeLists.txt:20 (PROTOBUF_GENERATE_CPP)


CMake Error at /app/fprime/cmake/prescan.cmake:127 (message):
-- Configuring incomplete, errors occurred!
See also "/workspaces/ros2_fprime_bridge/fprime_ws/spring/build-fprime-automatic-native/CMakeFiles/CMakeOutput.log".
  Failed to run prescan, cannot continue.
Call Stack (most recent call first):
  /app/fprime/cmake/FPrime.cmake:64 (perform_prescan)
  CMakeLists.txt:7 (include)


[ERROR] CMake erred with return code 1. Partial build cache remains. Run purge to clean-up.
The command '/bin/sh -c . /tmp/fprime-venv/bin/activate &&      cd fprime_ws/spring &&      fprime-util generate &&      fprime-util build' returned a non-zero code: 1
ERROR: Service 'foxglove_adapter' failed to build : Build failed
```
Any idea what I can do in order to fix this problem?

**Comment by mfigat** [comment]
Thanks for your help. I generated the protobuf files (I also had to change the path in the spring_defs.json), but I still get the error:
```bash
Errors were encountered while processing:
 python3-tornado
 python3-zope.interface
 python3-openssl
 python3-bcrypt
 python3-automat
 python3-hamcrest
 python3-wheel
 ros-humble-rosbridge-server
 python3-bson
 ros-humble-rosbridge-suite
 python3-twisted
 ros-humble-rosbridge-library
 python3-incremental
 python3-idna
 python3-pip
 python3-pyasn1
 ros-humble-rosapi
 python3-constantly
 python3.10-venv
 python3-pil:amd64
 python3-venv
 python3-pyasn1-modules
 python3-hyperlink
 python3-service-identity
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive  && apt-get install -y  --no-install-recommends    protobuf-compiler     autoconf     automake     libtool     make     g++     unzip     libprotobuf-dev     wget     openssh-server     curl     gnupg     git     build-essential     cmake     gdb-multiarch     default-jre     python3     python3-setuptools     python3-pip     python3-venv     ros-${ROS_DISTRO}-rosbridge-suite     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
ERROR: Service 'foxglove_adapter' failed to build : Build failed
```

**Comment by iftahnaf** [comment]
Glad to hear that you were able to solve the missing protobuf files.

Can you please attach the full log?

**Comment by mfigat** [comment]
[log.txt](https://github.com/lulav/ros2_fprime_bridge/files/13388531/log.txt)

**Comment by iftahnaf** [comment]
The `permisssion denied` errors suggests that there might be a problem with the docker installation.

Can you please check [this](https://stackoverflow.com/questions/75651585/docker-permissionerror-errno-13-permission-denied-command-returned-a-non) post, and let us know if it works for you?

**Comment by mfigat** [comment]
Thank you. I followed steps from:
- https://stackoverflow.com/questions/75651585/docker-permissionerror-errno-13-permission-denied-command-returned-a-non
- then: https://docs.docker.com/engine/install/ubuntu/
- and: https://docs.docker.com/engine/install/linux-postinstall/
- and finally: 
`sudo service docker restart`
It's much better, but still there is an error. This time with F Prime. I think there is a problem with the workspaces folder. You set the build directory at /workspaces/ros2_fprime_bridge/... .
[log2.txt](https://github.com/lulav/ros2_fprime_bridge/files/13389395/log2.txt)

**Comment by iftahnaf** [comment]
Hi @mfigat,

I added the generation of the protobuf files into the Dockerfile.
You can pull and test it now.

Please let me know if there are any other issues.

Thanks a lot for opening this issue.

**Comment by mfigat** [comment]
It works! Thank you very much.
How are you doing with the GDS connection issue?
